name: SQL Lint

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: ci/requirements-ci.txt

      - run: pip install -r ci/requirements-ci.txt
      - run: sqlfluff --version
      - run: sqlfluff lint easy medium hard
