name: SQL Lint

on:
  workflow_dispatch:  # 手動実行できるように（任意）

  pull_request:
    paths:
      - 'easy/*.sql'
      - 'easy/**/*.sql'
      - 'medium/*.sql'
      - 'medium/**/*.sql'
      - 'hard/*.sql'
      - 'hard/**/*.sql'

  push:
    branches:
      - main
      - 'problems/**'
      - 'chore/**'
    paths:
      - 'easy/*.sql'
      - 'easy/**/*.sql'
      - 'medium/*.sql'
      - 'medium/**/*.sql'
      - 'hard/*.sql'
      - 'hard/**/*.sql'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - run: pip install "sqlfluff==2.*"
      - run: sqlfluff --version

      # ← Lint対象も easy/ medium/ hard のみ
      - run: sqlfluff lint easy medium hard

